name: gapplus
description: Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
version: 1.0.0
homepage: https://github.com/odejinmi/gapplus

environment:

  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

